all:
	make --no-print-directory -f OVL_trans
	make --no-print-directory -f OVL_unchange
	

clean:
	  rm -fr a.out *.log *.vcd tee

help:
	make --no-print-directory -f OVL_trans help
	make --no-print-directory -f OVL_unchange  help
	


